// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DefaultSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void t1() {
    driver.get("https://www.w3schools.in/");
    driver.manage().window().setSize(new Dimension(1192, 1132));
    driver.findElement(By.id("SearchTerm")).click();
    driver.findElement(By.id("SearchTerm")).sendKeys("java tutorial");
    driver.findElement(By.id("SearchTerm")).sendKeys(Keys.ENTER);
    {
      WebElement element = driver.findElement(By.linkText("Java Tutorial"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("Java Tutorial")).click();
    vars.put("win4976", waitForWindow(2000));
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.switchTo().window(vars.get("win4976").toString());
    assertThat(driver.getTitle(), is("Java Tutorial - Learn Core & Advanced Java"));
    driver.findElement(By.cssSelector("p:nth-child(10) > a")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tr:nth-child(3) .copy"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void t2() {
    driver.get("https://www.w3schools.in/");
    driver.manage().window().setSize(new Dimension(1192, 1132));
    driver.findElement(By.cssSelector(".mb-4 > .text-center")).click();
    assertThat(driver.findElement(By.linkText("Learn CSS3")).getText(), is("Learn CSS3"));
    driver.findElement(By.linkText("Learn CSS3")).click();
    driver.findElement(By.linkText("CSS Tutorial")).click();
    {
      List<WebElement> elements = driver.findElements(By.linkText("CSS Practice Tests ❯"));
      assert(elements.size() > 0);
    }
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("CSS Practice Tests ❯")).click();
    vars.put("win4659", waitForWindow(2000));
    driver.switchTo().window(vars.get("win4659").toString());
    {
      WebElement element = driver.findElement(By.linkText("CSS Properties (Test 1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    assertThat(driver.getTitle(), is("CSS3 Practice Tests"));
  }
}
